export enum STATUS_ENUM {
  VALID = 1,
  INVALID = 2,
  INCOMPLETE = 3,
  PENDING = 4,
  OPEN = 5,
  VIEWED = 6,
}

export const statusEnumLabels = {
  [STATUS_ENUM.VALID]: "VALID",
  [STATUS_ENUM.INVALID]: "INVALID",
  [STATUS_ENUM.INCOMPLETE]: "INCOMPLETE",
  [STATUS_ENUM.PENDING]: "PENDING",
  [STATUS_ENUM.OPEN]: "OPEN",
  [STATUS_ENUM.VIEWED]: "VIEWED",
}
